//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayGetterConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDayGetter")]
    public interface IDayGetter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayGetter/GetDayInBulgarian", ReplyAction="http://tempuri.org/IDayGetter/GetDayInBulgarianResponse")]
        string GetDayInBulgarian(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayGetter/GetDayInBulgarian", ReplyAction="http://tempuri.org/IDayGetter/GetDayInBulgarianResponse")]
        System.Threading.Tasks.Task<string> GetDayInBulgarianAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayGetterChannel : DayGetterConsoleClient.ServiceReference1.IDayGetter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayGetterClient : System.ServiceModel.ClientBase<DayGetterConsoleClient.ServiceReference1.IDayGetter>, DayGetterConsoleClient.ServiceReference1.IDayGetter {
        
        public DayGetterClient() {
        }
        
        public DayGetterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayGetterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayGetterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayGetterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayInBulgarian(System.DateTime date) {
            return base.Channel.GetDayInBulgarian(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayInBulgarianAsync(System.DateTime date) {
            return base.Channel.GetDayInBulgarianAsync(date);
        }
    }
}
